[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mypackage"
version = "0.0.1"

[project.scripts]
test-script = "vehicle_crash_prevention:hello_world"

[project.entry-points."vehicles"]
drone= "vehicles.drone:Drone"
boatzzzz = "vehicles.boat:Boat"